blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/telekom/das-schiff-network-operator/tree/main/docs
    about: Please check the documentation before opening an issue
  - name: Security Vulnerabilities
    url: https://github.com/telekom/das-schiff-network-operator/security/advisories/new
    about: Report security vulnerabilities privately via Security Advisory
