apiVersion: network.schiff.telekom.de/v1alpha1
kind: RoutingTable
metadata:
  labels:
    app.kubernetes.io/name: routingtable
    app.kubernetes.io/instance: routingtable-sample
    app.kubernetes.io/part-of: network-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: network-operator
  name: routingtable-sample
spec:
  # TODO(user): Add fields here
