---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: layer2networkconfigurations.network.schiff.telekom.de
spec:
  group: network.schiff.telekom.de
  names:
    kind: Layer2NetworkConfiguration
    listKind: Layer2NetworkConfigurationList
    plural: layer2networkconfigurations
    shortNames:
    - layer2
    singular: layer2networkconfiguration
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.id
      name: VLAN
      type: integer
    - jsonPath: .spec.anycastGateways
      name: Gateway
      type: string
    - jsonPath: .spec.vrf
      name: VRF
      type: string
    - jsonPath: .spec.vni
      name: VNI
      priority: 10
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Layer2NetworkConfiguration is the Schema for the layer2networkconfigurations
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Layer2NetworkConfigurationSpec defines the desired state
              of Layer2NetworkConfiguration.
            properties:
              advertiseNeighbors:
                description: If desired network-operator advertises host routes for
                  local neighbors
                type: boolean
              anycastGateways:
                description: Anycast Gateway to configure on bridge
                items:
                  type: string
                type: array
              anycastMac:
                description: If anycast is desired, specify anycast gateway MAC address
                pattern: (?:[[:xdigit:]]{2}:){5}[[:xdigit:]]{2}
                type: string
              createMacVLANInterface:
                description: Create MACVLAN attach interface
                type: boolean
              id:
                description: VLAN Id of the layer 2 network
                type: integer
              mtu:
                description: Network interface MTU
                maximum: 9000
                minimum: 1000
                type: integer
              neighSuppression:
                description: Enable ARP / ND suppression
                type: boolean
              nodeSelector:
                description: Select nodes to create Layer2 network on
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to
                            a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
                x-kubernetes-map-type: atomic
              vni:
                description: VXLAN VNI Id for the layer 2 network
                maximum: 16777215
                minimum: 1
                type: integer
              vrf:
                description: VRF to attach Layer2 network to, default if not set
                type: string
            required:
            - id
            - mtu
            - vni
            type: object
          status:
            description: Layer2NetworkConfigurationStatus defines the observed state
              of Layer2NetworkConfiguration.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
